version: '3'
services:
  streamlit-llm-demos:
    container_name: streamlit-masterclass-langchain-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - .env
    ports:
       - "8501:8501"
    command: "streamlit run src/Start.py --server.port=8501 --server.address=0.0.0.0"